# SPDX-License-Identifier: CC0-1.0

repository:
  name: xkcd
  description: a mirror of xkcd [https://xkcd.com], including comics, title text, transcripts, JSON, etc.
  homepage: https://xkcd.com/
  topics: xkcd,comic,webcomic
  private: true
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: false
  allow_rebase_merge: false
  allow_merge_commit: true
  delete_branch_on_merge: false
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: false

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
    required_status_checks: null
    enforce_admins: null
    required_linear_history: true
    restrictions: null
    
collaborators:
  - username: gabldotink

labels: null
milestones: null
teams: null
