# SPDX-License-Identifier: CC0-1.0

# This file contains configuration for ls-lint [https://ls-lint.org/], which lints filenames and directory names.
# ls-lint should not be used in this repository until the lookaheads and lookbehinds in the regexes are converted to standard.

# The long regular expression matches filenames and directory names that meet all of the following criteria:
# - only contains the characters defined in the POSIX Portable Filename Character Set, consisting of the following (not including spaces):
#   A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
#   a b c d e f g h i j k l m n o p q r s t u v w x y z
#   0 1 2 3 4 5 6 7 8 9 . _ -
# - does not contain a hypen (-) as the first character of a filename
# - does not contain a period (.) as the final character of a filename
# - is not exclusively any of the following verbatim strings (case-insensitive, not including spaces); or, exclusively any of the following verbatim strings (case-insensitive, not including spaces) with a period after it, optionally followed by any other character:
#   CON  PRN  AUX  NUL
#   LPT0 LPT1 LPT2 LPT3 LPT4 LPT5 LPT6 LPT7 LPT8 LPT9
#   COM0 COM1 COM2 COM3 COM4 COM5 COM6 COM7 COM8 COM9
# - contains no less than 1 character
# - contains no more than 255 characters
# This regular expression does not take path seperators into account.

---

ls:
  .:
    .dir: 'regex:(?!-)(?!.*\.\.)(?![Cc][Oo][Nn](\..*)?)(?![Pp][Rr][Nn](\..*)?)(?![Aa][Uu][Xx](\..*)?)(?![Nn][Uu][Ll](\..*)?)(?![Ll][Pp][Tt][0-9](\..*)?)(?![Cc][Oo][Mm][0-9](\..*)?)[A-Za-z0-9._-]{1,255}(?<!\.)'
    .editorconfig: 'regex:.editorconfig'
    .gitattributes: 'regex:.gitattributes'
    .jpg: 'regex:(?!-)(?!.*\.\.)(?![Cc][Oo][Nn](\..*)?)(?![Pp][Rr][Nn](\..*)?)(?![Aa][Uu][Xx](\..*)?)(?![Nn][Uu][Ll](\..*)?)(?![Ll][Pp][Tt][0-9](\..*)?)(?![Cc][Oo][Mm][0-9](\..*)?)[A-Za-z0-9._-]{1,255}\.jpg'
    .json: 'regex:(?!-)(?!.*\.\.)(?![Cc][Oo][Nn](\..*)?)(?![Pp][Rr][Nn](\..*)?)(?![Aa][Uu][Xx](\..*)?)(?![Nn][Uu][Ll](\..*)?)(?![Ll][Pp][Tt][0-9](\..*)?)(?![Cc][Oo][Mm][0-9](\..*)?)[A-Za-z0-9._-]{1,255}\.json'
    .md: 'regex:(?!-)(?!.*\.\.)(?![Cc][Oo][Nn](\..*)?)(?![Pp][Rr][Nn](\..*)?)(?![Aa][Uu][Xx](\..*)?)(?![Nn][Uu][Ll](\..*)?)(?![Ll][Pp][Tt][0-9](\..*)?)(?![Cc][Oo][Mm][0-9](\..*)?)[A-Za-z0-9._-]{1,255}\.md'
    .pdf: 'regex:(?!-)(?!.*\.\.)(?![Cc][Oo][Nn]\.?)(?![Pp][Rr][Nn]\.?)(?![Aa][Uu][Xx]\.?)(?![Nn][Uu][Ll]\.?)(?![Ll][Pp][Tt][0-9]\.?)(?![Cc][Oo][Mm][0-9]\.?)[A-Za-z0-9._-]{1,255}\.pdf'
    .png: 'regex:(?!-)(?!.*\.\.)(?![Cc][Oo][Nn]\.?)(?![Pp][Rr][Nn]\.?)(?![Aa][Uu][Xx]\.?)(?![Nn][Uu][Ll]\.?)(?![Ll][Pp][Tt][0-9]\.?)(?![Cc][Oo][Mm][0-9]\.?)[A-Za-z0-9._-]{1,255}\.png'
    .txt: 'regex:(?!-)(?!.*\.\.)(?![Cc][Oo][Nn]\.?)(?![Pp][Rr][Nn]\.?)(?![Aa][Uu][Xx]\.?)(?![Nn][Uu][Ll]\.?)(?![Ll][Pp][Tt][0-9]\.?)(?![Cc][Oo][Mm][0-9]\.?)[A-Za-z0-9._-]{1,255}\.txt'
    .yml: 'regex:(?!-)(?!.*\.\.)(?![Cc][Oo][Nn]\.?)(?![Pp][Rr][Nn]\.?)(?![Aa][Uu][Xx]\.?)(?![Nn][Uu][Ll]\.?)(?![Ll][Pp][Tt][0-9]\.?)(?![Cc][Oo][Mm][0-9]\.?)[A-Za-z0-9._-]{1,255}\.yml'
  .github:
    .dir: 'regex:(?!-)(?!.*\.\.)(?![Cc][Oo][Nn](\..*)?)(?![Pp][Rr][Nn](\..*)?)(?![Aa][Uu][Xx](\..*)?)(?![Nn][Uu][Ll](\..*)?)(?![Ll][Pp][Tt][0-9](\..*)?)(?![Cc][Oo][Mm][0-9](\..*)?)[A-Za-z0-9._-]{1,255}(?<!\.)'
  licenses:
    .dir: 'regex:(?!-)(?!.*\.\.)(?![Cc][Oo][Nn](\..*)?)(?![Pp][Rr][Nn](\..*)?)(?![Aa][Uu][Xx](\..*)?)(?![Nn][Uu][Ll](\..*)?)(?![Ll][Pp][Tt][0-9](\..*)?)(?![Cc][Oo][Mm][0-9](\..*)?)[A-Za-z0-9._-]{1,255}(?<!\.)'
    .md: 'regex:(?!-)(?!.*\.\.)(?![Cc][Oo][Nn]\.?)(?![Pp][Rr][Nn]\.?)(?![Aa][Uu][Xx]\.?)(?![Nn][Uu][Ll]\.?)(?![Ll][Pp][Tt][0-9]\.?)(?![Cc][Oo][Mm][0-9]\.?)[A-Za-z0-9.-]{1,255}\.md'
  xkcd/en/comics:
    .dir: 'regex:[0-2][0-9][0-9][0-9]_[A-Za-z0-9_-]{1,250}(?<!\.)'
  xkcd/en/comics/*:
    .dir: 'regex:_plus'
    .jpg: 'regex:[0-2][0-9][0-9][0-9]_[A-Za-z0-9_-]{1,246}\.jpg'
    .json: 'regex:[0-2][0-9][0-9][0-9]_[A-Za-z0-9_-]{1,240}_info\.json'
    .png: 'regex:[0-2][0-9][0-9][0-9]_[A-Za-z0-9_-]{1,246}\.png'
    .txt: 'regex:[0-2][0-9][0-9][0-9]_[A-Za-z0-9_-]{1,246}\.txt'
  xkcd/en/comics/*/_plus:
    .jpg: 'regex:[0-2][0-9][0-9][0-9]_[A-Za-z0-9_-]{1,246}\.jpg'
    .txt: 'regex:[0-2][0-9][0-9][0-9]_[A-Za-z0-9_-]{1,246}\.txt'
  xkcd/en/print/xkcd_-_volume_0/pages/pdf:
    .dir: 'regex:(?!-)(?!.*\.\.)(?![Cc][Oo][Nn](\..*)?)(?![Pp][Rr][Nn](\..*)?)(?![Aa][Uu][Xx](\..*)?)(?![Nn][Uu][Ll](\..*)?)(?![Ll][Pp][Tt][0-9](\..*)?)(?![Cc][Oo][Mm][0-9](\..*)?)[A-Za-z0-9._-]{1,255}(?<!\.)''
    .pdf: 'regex:xkcd_-_volume_0_[01][0-9][0-9].pdf'
  xkcd/en/print/xkcd_-_volume_0/pages/png:
    .dir: 'regex:(?!-)(?!.*\.\.)(?![Cc][Oo][Nn](\..*)?)(?![Pp][Rr][Nn](\..*)?)(?![Aa][Uu][Xx](\..*)?)(?![Nn][Uu][Ll](\..*)?)(?![Ll][Pp][Tt][0-9](\..*)?)(?![Cc][Oo][Mm][0-9](\..*)?)[A-Za-z0-9._-]{1,255}(?<!\.)'
    .png: 'regex:xkcd_-_volume_0_[01][0-9][0-9].png'

ignore:
- .git
- .github/codeowners

...
